### PR TITLE
Add test case

### PR DESCRIPTION
**Pull request by andy840119**
1. add test cases.
2. fix some bug.

### CODE REVIEW

**Comment by InfinityGhost** [comment]
What's the purpose of all of this?

**Comment by mrflashstudio** [comment]
While I appreciate the work you have done, I don’t think we need test cases now. The library is almost in it's completed state.

**Comment by andy840119** [comment]
Hmm...
`Test case` is the convenience way to make sure someone's PR won't break your code.
If someone find bug he can add test case to make sure it is fixed (and not break the code).
.
And actually i found few bugs by writing testcase.

**Comment by mrflashstudio** [comment]
As I already stated: this library is almost done. I won't be making any major changes that may potentially break something.
If you encounter a bug, please report it via issue or make a PR that fixes it.

**Comment by andy840119** [comment]
Hmm...
Okey

**Comment by InfinityGhost** [comment]
Going back and looking at this pull request, this actually might be a good idea to merge. It won't break anything as it's an extra project, and we really could use it for improving the library.

**Comment by mrflashstudio** [comment]
Superseded by #25.

**Pull request closed without merging**
