### PR TITLE
Beatmap writer

### PR DESCRIPTION
**Pull request by InfinityGhost**
Added a whole lot of stuff here!

- Made `Write(path)` use the BeatmapWriter class and write to file.
- Changed most arrays into Lists where it made most sense.
- Proper formatting of each object.

TODO:
- Add other modes' objects to HitObject writing.
- Add proper type implementation for HitObjects
  - Should be a proper bitmap, (I'm not really sure how to pull that off)
    - Bit 0 (1): circle.
    - Bit 1 (2): slider.
    - Bit 2 (4): new combo.
    - Bit 3 (8): spinner.
    - Bits 4-6 (16, 32, 64) form a 3-bit number (0-7) that chooses how many combo colours to skip.
    - Bit 7 (128) is for an osu!mania hold note.

### CODE REVIEW

**Comment by mrflashstudio** [comment]
What did you meant by "Add proper type implementation for HitObjects"?

**Comment by InfinityGhost** [comment]
It would be easiest to use exactly whats documented in the [.osu wiki](https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)#common-structure), especially for the type portion of the common structure. I'm not sure if it has been implemented yet, and there seems to be a lack of color skip property to add it in properly.

**Comment by InfinityGhost** [comment]
The common syntax for all hitobjects `(x,y,time,type,hitSound...,extras)` contains the `Type` property which follows the bitmap I commented in the PR

**Comment by mrflashstudio** [comment]
Regarding the color skip. We have ``ComboOffset`` property in ``StandardHitObject`` and ``CatchHitObject`` classes, which is color skip itself. I already added it to the PR.

**Comment by InfinityGhost** [comment]
We still need to write some sort of byte writer for the "bitmap" to mathematically do it properly, I'll look into it a bit, haven't worked with that kinda stuff yet

**Comment by InfinityGhost** [comment]
Looked at what you've done, seems to work but I'm sure we could clean this up

**Comment by mrflashstudio** [comment]
Yeah, i agree. My code is kinda messy, especially events section.

**Comment by InfinityGhost** [comment]
Made the code a bit prettier by creating local extension methods so we can just write .Format() to the end to use the proper format of the value

**Comment by InfinityGhost** [comment]
For simplicity, we should probably make all non-standard mode objects (except for some mania objects) inherit their standard counterpart. This would let use be able to use something like the taiko drumroll and use the slider writer for it since they use the same format the end.

**Comment by mrflashstudio** [comment]
Not sure about inheriting standard objects. Maybe we can just make base classes like ``HitObject`` class for circle, slider, spinner and inherit them instead?

**Comment by InfinityGhost** [comment]
I think that would be better actually, would simplify writing to files.

**Comment by mrflashstudio** [comment]
I've encountered a problem when I want to inherit both the ``StandardHitObject`` and ``Slider`` classes inside the ``StandardSlider`` class. I thought about deleting classes such as ``StandardHitObject``, ``TaikoHitObject``, etc. But because of that, the user will no longer be able to check to which ruleset this object belongs. So right now I'm not very sure what to do.

**Comment by mrflashstudio** [comment]
Misclicked, sorry.

**Comment by InfinityGhost** [comment]
Its unlikely you'll ever see a use case of the individual objects, plus the mode property already tells you what kind of object it will be represented as

**Comment by InfinityGhost** [comment]
My suggestion is to make a base class for all of the objects, just "HitObject" which includes X, Y, start time, object type (that weird bitmap), hitsound, and extras. I'm gonna try to write out some sort of chart to make it simpler

**Comment by InfinityGhost** [comment]
Object inheritance flow chart
smartd 1_2018-12-28_20-50-25

**Comment by InfinityGhost** [comment]
Take a peek at my [branch](https://github.com/InfinityGhost/OsuParsers/tree/objects-rewrite), attempting to rewrite them as needed.

**Comment by mrflashstudio** [comment]
Looks good so far, good work.

**Comment by InfinityGhost** [comment]
Quite lost on the decoder portion of the code in my branch, gonna need help there.

**Comment by mrflashstudio** [comment]
Okay, then I'll commit your changes and try to deal with the decoder.

**Comment by mrflashstudio** [comment]
Okay, everything seems to be updated.

**Comment by mrflashstudio** [comment]
By the way, shouldn't ``TaikoHit``, ``CatchFruit`` and ``ManiaHit`` classes inherit ``Circle`` class and not ``HitObject``?

**Comment by InfinityGhost** [comment]
you're correct here, fix that lol

**Comment by InfinityGhost** [comment]
Everything seems to be working in the writing portion for beatmaps, can't find any case of it failing yet.

**Comment by InfinityGhost** [comment]
The IsBig property of TaikoHits should be determined by the hitsound of the object

**Comment by InfinityGhost** [comment]
I've noticed a flaw where we can't have multiple HitSounds on objects like we should be able to. I've only got a getter for **IsBig** written because we can't add another HitSound on top (unless I'm just oblivious to it, I'm not really sure how enums work).
I believe HitSoundType might need to be a class with bools representing whether each type of HitSound is enabled
Another note, Color should be determined by hitsound as well, which runs into the issue yet again

**Comment by mrflashstudio** [comment]
Enums can have multiple values. So, for example, you can add some item to an existing enum using the += operator: ``HitSound += (int)HitSoundType.Whistle`` I'm bad at explaining, so maybe [this article](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/enumeration-types) will help you better. And, as far as I know, osu! can't have more than one HitSound per HitObject.

**Comment by InfinityGhost** [comment]
It certainly can have multiple hitsounds, especially since thats the only way you could map taiko
image

**Comment by mrflashstudio** [comment]
Tested on all rulesets and everything seems to be working as it should.

**Comment by InfinityGhost** [comment]
The real question, is it ready to merge?

**Comment by mrflashstudio** [comment]
Pretty much, i'd say. Just waiting for your confirmation.

**Comment by InfinityGhost** [comment]
I haven't found a case of it not working since so I'd say merge it

**Pull request merged**
