### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by InfinityGhost**
I went and cleaned up some of the FormatHelper class to make the code more uniform and follow the same style.

### CODE REVIEW

**Comment by InfinityGhost** [comment]
This also satisfies a CodeFactor code format issue

**Comment by mrflashstudio** [comment]
Is it ready to merge?

**Comment by InfinityGhost** [comment]
Let me do some quick review to see if I got everything

**Comment by InfinityGhost** [comment]
I can say that everything is working, but I'd test it from your end too.

**Comment by mrflashstudio** [comment]
Everything works as expected at my end too. Good job.

**Pull request merged**
