### PR TITLE
Add Unit Tests

### PR DESCRIPTION
**Pull request by InfinityGhost**
Tests can help us confirm that all of our changes will work consistently. I wrote some test cases for beatmaps that downloads the beatmap from the osu! website then actively parses it. It also tests 10 random beatmaps from the website, which could eventually help us discover more bugs.

### CODE REVIEW

**Comment by InfinityGhost** [comment]
These tests also allow us to benchmark the speed at which the parser reads the maps, so we can optimize it more.

**Comment by mrflashstudio** [comment]
Looks awesome! Can this be merged?

**Comment by InfinityGhost** [comment]
It should be ready to be merged at this point.

**Comment by mrflashstudio** [comment]
Great, thank you!

**Pull request merged**
